version: '3.1'
services:

  stats-server:
    build: ./stat-service/stat-service-server
    image: server-image
    container_name: serverContainer
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - DB_USERNAME=root
      - DB_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: dbContainer
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

